<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.25"/>
    <xacro:property name="chassis_width" value="0.15"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.12"/>
    <!-- <xacro:property name="wheel_offset_y" value="0.1485"/> -->
    <xacro:property name="wheel_offset_y" value="0.1"/>
    <xacro:property name="wheel_offset_z" value="0.05"/>


    <!-- BASE LINK -->
    <link name="base_link">

    </link>
    <!-- ******************************************************************************************************************** -->




    <!-- BASE_FOOTPRINT LINK -->    
    <!-- ******************************************************************************************************************** -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">

    </link>
    <!-- ******************************************************************************************************************** -->




    <!-- CHASSIS LINK -->
    <!-- ******************************************************************************************************************** -->
    <!-- <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">

    </link> -->
    <!-- ******************************************************************************************************************** -->




    <!-- BOTTOM CHASSIS LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="bottom_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="bottom_chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="bottom_chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 -${pi/2}"/>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/bottom_plate.stl" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/bottom_plate.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="bottom_chassis">
        <material>Gazebo/Orange</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- TOP CHASSIS LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="top_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="top_chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="top_chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height*1.2}" rpy="0 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/top_plate.stl" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/top_plate.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="top_chassis">
        <material>Gazebo/Orange</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- FRONT LEFT WHEEL LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="front_left_motor"/>
        <child link="front_left_wheel"/>
        <origin xyz="0.0165 -0.03 0" rpy="${3*pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/components/wheel.stl" scale="1 1 1"/>                           
            </geometry>                
            <material name="blue"/> 
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- REAR LEFT WHEEL LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="rear_left_motor"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0.0165 -0.03 0" rpy="${3*pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/components/wheel.stl" scale="1 1 1"/>                           
            </geometry>                
            <material name="blue"/> 
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- FRONT RIGHT WHEEL LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="front_right_motor"/>
        <child link="front_right_wheel"/>
        <origin xyz="0.0165 -0.03 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/components/wheel.stl" scale="1 1 1"/>                           
            </geometry>                
            <material name="blue"/> 
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- REAR RIGHT WHEEL LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="rear_right_motor"/>
        <child link="rear_right_wheel"/>
        <origin xyz=".0165 -0.03 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/components/wheel.stl" scale="1 1 1"/>                           
            </geometry>                
            <material name="blue"/> 
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- ******************************************************************************************************************** -->




    <!-- REAR RIGHT MOTOR LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="rear_right_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right_motor"/>
        <origin xyz="${-wheel_offset_x/2.3} ${-wheel_offset_y+0.065} ${-wheel_offset_z+0.035}" rpy="0 0 0" />
    </joint>

    <link name="rear_right_motor">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/motor.stl" scale="1 1 1"/>                          
            </geometry>                
            <material name="cyan"/>
        </visual>
    </link>
    <!-- ******************************************************************************************************************** -->




    <!-- REAR LEFT MOTOR LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="rear_left_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left_motor"/>
        <origin xyz="${-wheel_offset_x/2.3} ${wheel_offset_y-0.065} ${-wheel_offset_z+0.035}" rpy="${pi} 0 0" />
    </joint>

    <link name="rear_left_motor">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/motor.stl" scale="1 1 1"/>                          
            </geometry>                
            <material name="cyan"/>
        </visual>
    </link>
    <!-- ******************************************************************************************************************** -->




    <!-- FRONT RIGHT MOTOR LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="front_right_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_motor"/>
        <origin xyz="${wheel_offset_x/1.95} ${-wheel_offset_y+0.065} ${-wheel_offset_z+0.035}" rpy="${pi} 0 ${pi}" />
    </joint>

    <link name="front_right_motor">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/motor.stl" scale="1 1 1"/>                          
            </geometry>                
            <material name="cyan"/>
        </visual>
    </link>
    <!-- ******************************************************************************************************************** -->




    <!-- FRONT LEFT MOTOR LINK -->
    <!-- ******************************************************************************************************************** -->
    <joint name="front_left_motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_motor"/>
        <origin xyz="${wheel_offset_x/1.95} ${wheel_offset_y-0.065} ${-wheel_offset_z+0.035}" rpy="0 0 ${pi}" />
    </joint>

    <link name="front_left_motor">
        <visual>
            <geometry>
                <mesh filename="package://my_bot_description/description/meshes/bot/motor.stl" scale="1 1 1"/>                          
            </geometry>                
            <material name="cyan"/>
        </visual>
    </link>



</robot>